services:
  app:
    image: tu-usuario/gaslighting-app:latest # La imagen que se sube a Docker Hub
    container_name: gaslighting_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: gaslighting_db
    environment:
      POSTGRES_DB: gaslighting
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: "Cd@69440"
    volumes:
      - ./database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
      - postgres_data:/var/lib/postgresql/data